export const GET_SUITES = 'GET_SUITES';
export const TOGGLE_FOLLOW = 'TOGGLE_FOLLOW';
export const SHOW_ONLY_SELECTED_SUITES = 'SHOW_ONLY_SELECTED_SUITES';
export const SHOW_ALL_SUITES = 'SHOW_ALL_SUITES';
